/* Standalone Frontend Mock Database & Storage Utilities */

export const INITIAL_PRODUCTS = [
  {
    _id: 'prod_1',
    name: 'Oversized Cotton Hoodie',
    slug: 'oversized-cotton-hoodie',
    description:
      'A heavyweight, garment-dyed hoodie cut for an oversized, streetwear-inspired fit. Made from 100% brushed cotton fleece for everyday comfort.',
    shortDescription: 'Heavyweight oversized fleece hoodie.',
    category: 'unisex',
    subCategory: 'hoodies',
    price: 68,
    compareAtPrice: 85,
    images: [{ url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800', alt: 'Oversized Cotton Hoodie' }],
    variants: [
      { _id: 'v1_1', size: 'S', color: 'Black', colorHex: '#111111', stock: 12 },
      { _id: 'v1_2', size: 'M', color: 'Black', colorHex: '#111111', stock: 20 },
      { _id: 'v1_3', size: 'L', color: 'Black', colorHex: '#111111', stock: 15 },
      { _id: 'v1_4', size: 'M', color: 'Sand', colorHex: '#d8c3a5', stock: 10 },
    ],
    tags: ['hoodie', 'streetwear', 'oversized'],
    material: '100% Heavyweight Brushed Cotton Fleece (450 GSM)',
    featured: true,
    isNewArrival: true,
    reviews: [
      {
        _id: 'rev_1',
        user: { name: 'Zayn R.' },
        rating: 5,
        comment: 'The silhouette and drape on this hoodie is unmatched. Heavyweight quality that feels straight off the runway.',
        createdAt: '2026-08-10T12:00:00Z',
      },
    ],
  },
  {
    _id: 'prod_2',
    name: 'Tailored Wool-Blend Overcoat',
    slug: 'tailored-wool-blend-overcoat',
    description:
      'A refined, minimalist overcoat tailored from a premium wool blend. Structured shoulders and a clean silhouette make this a cold-weather staple.',
    shortDescription: 'Minimalist tailored wool-blend overcoat.',
    category: 'men',
    subCategory: 'outerwear',
    price: 189,
    compareAtPrice: 240,
    images: [{ url: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800', alt: 'Wool Overcoat' }],
    variants: [
      { _id: 'v2_1', size: 'M', color: 'Charcoal', colorHex: '#36454f', stock: 8 },
      { _id: 'v2_2', size: 'L', color: 'Charcoal', colorHex: '#36454f', stock: 6 },
      { _id: 'v2_3', size: 'XL', color: 'Camel', colorHex: '#c19a6b', stock: 5 },
    ],
    tags: ['coat', 'outerwear', 'formal'],
    material: '70% Italian Wool, 30% Polyester Blend',
    featured: true,
    isNewArrival: false,
    reviews: [],
  },
  {
    _id: 'prod_3',
    name: 'Ribbed Knit Midi Dress',
    slug: 'ribbed-knit-midi-dress',
    description:
      'A body-skimming ribbed midi dress with a soft stretch knit. Effortlessly transitions from day to evening.',
    shortDescription: 'Soft-stretch ribbed knit midi dress.',
    category: 'women',
    subCategory: 'dresses',
    price: 74,
    compareAtPrice: 95,
    images: [{ url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', alt: 'Ribbed Knit Dress' }],
    variants: [
      { _id: 'v3_1', size: 'S', color: 'Olive', colorHex: '#708238', stock: 14 },
      { _id: 'v3_2', size: 'M', color: 'Olive', colorHex: '#708238', stock: 18 },
      { _id: 'v3_3', size: 'M', color: 'Black', colorHex: '#111111', stock: 16 },
    ],
    tags: ['dress', 'knitwear', 'minimal'],
    material: '95% Viscose, 5% Elastane',
    featured: true,
    isNewArrival: true,
    reviews: [],
  },
  {
    _id: 'prod_4',
    name: 'Relaxed Fit Denim Jeans',
    slug: 'relaxed-fit-denim-jeans',
    description:
      'Rigid selvedge denim jeans with a relaxed leg and mid-rise waist. Built to soften and fade beautifully over time.',
    shortDescription: 'Relaxed-fit rigid selvedge denim.',
    category: 'men',
    subCategory: 'denim',
    price: 92,
    compareAtPrice: 120,
    images: [{ url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800', alt: 'Denim Jeans' }],
    variants: [
      { _id: 'v4_1', size: '30', color: 'Indigo', colorHex: '#3f5b8a', stock: 10 },
      { _id: 'v4_2', size: '32', color: 'Indigo', colorHex: '#3f5b8a', stock: 22 },
      { _id: 'v4_3', size: '34', color: 'Indigo', colorHex: '#3f5b8a', stock: 14 },
    ],
    tags: ['denim', 'jeans'],
    material: '100% Japanese Rigid Cotton Selvedge Denim',
    featured: false,
    isNewArrival: false,
    reviews: [],
  },
  {
    _id: 'prod_5',
    name: 'Minimal Leather Tote',
    slug: 'minimal-leather-tote',
    description:
      'A structured full-grain leather tote with an interior laptop sleeve. Understated hardware, made to age gracefully.',
    shortDescription: 'Structured full-grain leather tote.',
    category: 'accessories',
    subCategory: 'bags',
    price: 145,
    compareAtPrice: 180,
    images: [{ url: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800', alt: 'Leather Tote' }],
    variants: [
      { _id: 'v5_1', size: 'One Size', color: 'Tan', colorHex: '#d2b48c', stock: 9 },
      { _id: 'v5_2', size: 'One Size', color: 'Black', colorHex: '#111111', stock: 11 },
    ],
    tags: ['bag', 'leather', 'accessories'],
    material: '100% Full-Grain Calfskin Leather',
    featured: true,
    isNewArrival: false,
    reviews: [],
  },
  {
    _id: 'prod_6',
    name: 'Court Leather Sneakers',
    slug: 'court-leather-sneakers',
    description:
      'Clean, low-profile leather sneakers with a cupsole construction. A minimal silhouette that pairs with everything.',
    shortDescription: 'Low-profile leather court sneakers.',
    category: 'footwear',
    subCategory: 'sneakers',
    price: 118,
    compareAtPrice: null,
    images: [{ url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', alt: 'Leather Sneakers' }],
    variants: [
      { _id: 'v6_1', size: '40', color: 'White', colorHex: '#f5f5f5', stock: 13 },
      { _id: 'v6_2', size: '41', color: 'White', colorHex: '#f5f5f5', stock: 17 },
      { _id: 'v6_3', size: '42', color: 'White', colorHex: '#f5f5f5', stock: 20 },
      { _id: 'v6_4', size: '43', color: 'White', colorHex: '#f5f5f5', stock: 9 },
    ],
    tags: ['sneakers', 'footwear', 'minimal'],
    material: 'Calfskin Leather Upper & Vulcanized Rubber Cupsole',
    featured: false,
    isNewArrival: true,
    reviews: [],
  },
];

export const INITIAL_ORDERS = [
  {
    _id: 'ord_1001',
    orderNumber: '1001',
    user: { _id: 'usr_admin', name: 'Shahmir (Admin)', email: 'ashahmir467@gmail.com' },
    items: [
      {
        product: 'prod_1',
        name: 'Oversized Cotton Hoodie',
        slug: 'oversized-cotton-hoodie',
        image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
        price: 68,
        quantity: 1,
        size: 'M',
        color: 'Black',
      },
    ],
    shippingAddress: {
      fullName: 'Shahmir Admin',
      phone: '+92 300 1234567',
      line1: '15 Atelier Street',
      city: 'Paris',
      state: 'Île-de-France',
      postalCode: '75001',
      country: 'France',
    },
    paymentMethod: 'mock_card',
    itemsPrice: 68,
    shippingPrice: 9.99,
    taxPrice: 5.44,
    totalPrice: 83.43,
    isPaid: true,
    paidAt: '2026-08-11T10:00:00Z',
    status: 'shipped',
    statusHistory: [{ status: 'confirmed' }, { status: 'processing' }, { status: 'shipped' }],
    createdAt: '2026-08-11T10:00:00Z',
  },
];

export const DEMO_COUPONS = {
  URBAN15: { type: 'percent', discount: 15, description: '15% Off Your Entire Cart' },
  FREESHIP: { type: 'freeship', description: 'Complimentary Express Shipping' },
  WELCOME10: { type: 'percent', discount: 10, description: '10% Welcome Discount' },
};
